### ISSUE TITLE
Send with callback

### ISSUE THREAD

**Issue by THE-KONDRAT** [baking-bad/pysignalr#11]
Hi. Can you give me an example how to call "send" method that returns some value?

In my hub i have that method

```csharp
public async Task<string> A()
{
    var message = $"Recieved: [{DateTime.Now}]";
    return $"C# -> {message}";
}
```

in python i should use something like that except questions.
```python
???
await client.send('A', [], ???)
print(???)
```
What should i write instead of questions?

**Comment by droserasprout** [comment]
Hi! You need to pass a callback accepting a single `CompletionMessage`. Here's an example of how we use `.send()` ([full source](https://github.com/dipdup-io/dipdup/blob/63f6786bb5c49f7b3e23040b42b92322f2e8af57/src/dipdup/datasources/tezos_tzkt.py#L1067)). Hope it helps!

```python
async def _subscribe(self, subscription: TzktSubscription) -> None:
    self._logger.debug('Subscribing to %s', subscription)
    method = subscription.method
    request: list[dict[str, Any]] = subscription.get_request()

    event = Event()

    async def _on_subscribe(message: CompletionMessage) -> None:
        if message.error:
            await self._on_error(message)
        level = cast(int, message.result)
        self._subscriptions.set_sync_level(subscription, level)
        event.set()

    await self._send(method, request, _on_subscribe)
    await event.wait()
```

**Comment by THE-KONDRAT** [comment]
> Hi! You need to pass a callback accepting a single `CompletionMessage`. Here's an example of how we use `.send()` ([full source](https://github.com/dipdup-io/dipdup/blob/63f6786bb5c49f7b3e23040b42b92322f2e8af57/src/dipdup/datasources/tezos_tzkt.py#L1067)). Hope it helps!

Thanks. It works for me.
I don't know how to make this work without a method declaration (something like ```async () => {...}``` in c#), but even so it already works.

Here's my code.
```python
async def get_setup() -> None:
    async def setup_callback(message: CompletionMessage) -> None:
        if message.error:
            await on_error(message)
            return
        try:
            await on_setting_up([message.result])
        except KeyError:
            print("Settings object corrupted.")
    await client.send('SetupRequired', [], setup_callback)
```
