### ISSUE TITLE
Initializing SignalR client for reconnect and keep-alive

### ISSUE THREAD

**Issue by wmmihaa** [baking-bad/pysignalr#21]
We're using `signalrcore` as our SignalR library today, but as it's not maintained any longer and as this library seams much more modern and up to date. we're considering migrating to `pysignalr` instead. We've done some initial testing and it all seams great, but we cannot find any documentation about setting it up for **Reconnect** and **Keep-alive**. Are there any samples of doing this?

This is our current code for initializing the SignalR client:
```python
self.connection = HubConnectionBuilder()\
            .with_url(signalr_uri, options={"verify_ssl": False}) \
            .with_automatic_reconnect({
                "type": "raw", # "raw" means it will continue to call the hub
                "enable_trace": False,
                "keep_alive_interval": 15,
                "reconnect_interval": 5
            }).build()

#...
self.connection.start()
```
Is there and equivalent sample?
Thank you

**Comment by droserasprout** [comment]
Retry with backoff implemented in 1.1.0. Use retry_sleep/retry_count/retry_multiplier arguments of the client.
