### ISSUE TITLE
Accesstoken factory and connection id

### ISSUE THREAD

**Issue by chrisism** [baking-bad/pysignalr#4]
It would be nice to be able to apply an accesstoken factory method, generating the authentication tokens for secured connections.
Also we need a way to get the connection id to setup grouped and channel specific communication.

**Comment by droserasprout** [comment]
Hi, and thanks for reaching out!

These features seem to be relatively easy to implement since they were present in mandrewcito/signalrcore, which this project is inspired. However, PRs are very welcome since we don't need this functionality in our project.

**Comment by mgkeeley** [comment]
I am interested in using this package, and need this auth feature for our project also. 

However, may I suggest that the token method is made async?  Often the token method would make calls to update a refresh token, or exchange credentials for a access token.
